/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_typoface_jwoff2_WOFF2 */

#ifndef _Included_com_typoface_jwoff2_WOFF2
#define _Included_com_typoface_jwoff2_WOFF2
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_typoface_jwoff2_WOFF2
 * Method:    convertTTF2WOFF2
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_typoface_jwoff2_WOFF2_convertTTF2WOFF2Byte
  (JNIEnv *, jclass, jbyteArray);


/*
 * Class:     com_typoface_jwoff2_WOFF2
 * Method:    convertTTF2WOFF2
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_typoface_jwoff2_WOFF2_convertTTF2WOFF2
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_typoface_jwoff2_WOFF2
 * Method:    convertWOFF2ToTTF
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_typoface_jwoff2_WOFF2_convertWOFF2ToTTF
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
